### ISSUE TITLE
Dataset and Code Requirement

### ISSUE THREAD

**Issue by Disguiser15** [Buki2/STAN#1]
Hello, I am interested in the scene text in REC and want to follow the work. When will the dataset and code be available?

**Comment by Buki2** [comment]
Thank you for your interest in our work.

We are sorry for the inconvenience. We will do our best to upload the dataset and code by the end of this month.

**Comment by Buki2** [comment]
Please give us a few more weeks, and we confirm that December 31 is the hard deadline. Thank you!

**Comment by Disguiser15** [comment]
Thank you for your reply! I am already eagerly awaiting the resource of your paper.
